version: '3'

services:
        coredns:
                image: soaryu/nacos-coredns:latest
                container_name: nacos-coredns
                restart: always
                network_mode: "bridge"
                expose:
                  - '53'
                  - '53/udp'
                ports:
                  - "1053:53"
                  - "1053:53/udp"
                volumes:
                  - ./conf/Corefile:/etc/coredns/Corefile
